# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'PebbleBuddy' do
pod 'PebbleKit'

end

target 'PebbleBuddyTests' do

end

target 'PebbleBuddyUITests' do

end

